<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" ignored="0" total="8" passed="5">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="17999" started-at="2022-02-21T22:11:40Z" finished-at="2022-02-21T22:11:58Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="17999" started-at="2022-02-21T22:11:40Z" finished-at="2022-02-21T22:11:58Z">
      <class name="search.SearchText">
        <test-method status="PASS" signature="getBrowser()[pri:0, instance:search.SearchText@1990a65e]" name="getBrowser" is-config="true" duration-ms="2786" started-at="2022-02-21T22:11:46Z" finished-at="2022-02-21T22:11:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getBrowser -->
        <test-method status="PASS" signature="getPageTitle()[pri:0, instance:search.SearchText@1990a65e]" name="getPageTitle" duration-ms="8" started-at="2022-02-21T22:11:48Z" finished-at="2022-02-21T22:11:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getPageTitle -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:search.SearchText@1990a65e]" name="tearDown" is-config="true" duration-ms="961" started-at="2022-02-21T22:11:48Z" finished-at="2022-02-21T22:11:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="getBrowser()[pri:0, instance:search.SearchText@1990a65e]" name="getBrowser" is-config="true" duration-ms="2423" started-at="2022-02-21T22:11:49Z" finished-at="2022-02-21T22:11:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getBrowser -->
        <test-method status="PASS" signature="getScreenshot()[pri:0, instance:search.SearchText@1990a65e]" name="getScreenshot" duration-ms="1272" started-at="2022-02-21T22:11:52Z" finished-at="2022-02-21T22:11:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getScreenshot -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:search.SearchText@1990a65e]" name="tearDown" is-config="true" duration-ms="926" started-at="2022-02-21T22:11:53Z" finished-at="2022-02-21T22:11:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="getBrowser()[pri:0, instance:search.SearchText@1990a65e]" name="getBrowser" is-config="true" duration-ms="2311" started-at="2022-02-21T22:11:54Z" finished-at="2022-02-21T22:11:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getBrowser -->
        <test-method status="PASS" signature="getSearchResult()[pri:0, instance:search.SearchText@1990a65e]" name="getSearchResult" duration-ms="1180" started-at="2022-02-21T22:11:56Z" finished-at="2022-02-21T22:11:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getSearchResult -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:search.SearchText@1990a65e]" name="tearDown" is-config="true" duration-ms="1008" started-at="2022-02-21T22:11:57Z" finished-at="2022-02-21T22:11:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- search.SearchText -->
      <class name="apitest.APITest">
        <test-method status="FAIL" signature="findOrderById()[pri:0, instance:apitest.APITest@782663d3]" name="findOrderById" duration-ms="2084" started-at="2022-02-21T22:11:40Z" finished-at="2022-02-21T22:11:43Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at apitest.APITest.findOrderById(APITest.java:51)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- findOrderById -->
        <test-method status="PASS" signature="getAvailablePetsByStatus()[pri:0, instance:apitest.APITest@782663d3]" name="getAvailablePetsByStatus" duration-ms="1038" started-at="2022-02-21T22:11:43Z" finished-at="2022-02-21T22:11:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getAvailablePetsByStatus -->
        <test-method status="FAIL" signature="getInventory()[pri:0, instance:apitest.APITest@782663d3]" name="getInventory" duration-ms="610" started-at="2022-02-21T22:11:44Z" finished-at="2022-02-21T22:11:44Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at apitest.APITest.getInventory(APITest.java:90)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getInventory -->
        <test-method status="PASS" signature="getPetDetails()[pri:0, instance:apitest.APITest@782663d3]" name="getPetDetails" duration-ms="625" started-at="2022-02-21T22:11:44Z" finished-at="2022-02-21T22:11:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getPetDetails -->
        <test-method status="FAIL" signature="userLogin()[pri:0, instance:apitest.APITest@782663d3]" name="userLogin" duration-ms="743" started-at="2022-02-21T22:11:45Z" finished-at="2022-02-21T22:11:46Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at apitest.APITest.userLogin(APITest.java:78)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- userLogin -->
      </class> <!-- apitest.APITest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
